- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
    dataloader_config:
      num_workers: 32
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
  model:
    name: "xception71_noisy_heading_retrained_unperturbed"
- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
    dataloader_config:
      num_workers: 32
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
  model:
    name: "xception71_no_past_retrained_unperturbed"
- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
    dataloader_config:
      num_workers: 32
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
  model:
    name: "xception71_no_road_retrained_unperturbed"
- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
    dataloader_config:
      num_workers: 32
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
  model:
    name: "xception71_noisy_heading_retrained"
- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
    dataloader_config:
      num_workers: 32
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
  model:
    name: "xception71_no_past_retrained"
- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
    dataloader_config:
      num_workers: 32
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
  model:
    name: "xception71_no_road_retrained"
#- data_config:
#    dataset_config:
#      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
#    dataloader_config:
#      num_workers: 32
#  output_config:
#    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
#  model:
#    name: "xception71_noisy_heading"
#- data_config:
#    dataset_config:
#      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
#    dataloader_config:
#      num_workers: 8
#  output_config:
#    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
#  model:
#    name: "xception71_no_past"
#- data_config:
#    dataset_config:
#      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
#    dataloader_config:
#      num_workers: 8
#  output_config:
#    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
#  model:
#    name: "xception71_no_road"
#- data_config:
#    dataset_config:
#      data_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/predictions/"
#    dataloader_config:
#      num_workers: 8
#  output_config:
#    out_path: "/home/manolotis/sandbox/robustness_benchmark/motionCNN/evaluations/"
#  model:
#    name: "xception71"