data_config:
  dataset_config:
    data_path: "/home/manolotis/sandbox/scenario_based_evaluation/motionCNN/predictions/"
  dataloader_config:
    num_workers: 32
output_config:
  out_path: "/home/manolotis/sandbox/scenario_based_evaluation/motionCNN/evaluations/"
models:
  - name: "xception71"
#  - name: "xception71_no_past"
#  - name: "xception71_no_road"
#  - name: "xception71_noisy_heading"
#  - name: "xception71_no_past_retrained"
#  - name: "xception71_no_road_retrained"
#  - name: "xception71_noisy_heading_retrained"
#  - name: "xception71_no_past_retrained_unperturbed"
#  - name: "xception71_no_road_retrained_unperturbed"
#  - name: "xception71_noisy_heading_retrained_unperturbed"